### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by acyc070** [AtDeadOfNight/russian-dub-release#1]
Почему в файлах игры есть фразы где Майя просит друзей идти в кладовки, призраки говорят 'нет'?

**Comment by VityaSchel** [comment]
> Почему в файлах игры есть фразы где Майя просит друзей идти в кладовки, призраки говорят 'нет'?

Потому что так было в оригинале

**Comment by acyc070** [comment]
по крайней мере я никогда не слышал их в игре

**Comment by VityaSchel** [comment]
> по крайней мере я никогда не слышал их в игре

верно, Тим Фоллин их не использовал
